version: "3.7"
services:
  rabbitmq1:
      image: rabbitmq:3-management
      container_name: rabbitmq1
      extra_hosts: [ "host.docker.internal:172.17.0.1" ]
      hostname: rabbitmq1
      ports:
        - 5672:5672
        - 15672:15672
      volumes:
        - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
      networks:
        - sail

networks:
    sail:
        driver: bridge
